### ISSUE TITLE
TestVector test fails.

### ISSUE THREAD

**Issue by klauspost** [akualab/narray#13]
'master' fails this test:

```
c:\GoPath\src\github.com\akualab\narray>go test
--- FAIL: TestVector (0.00s)
panic: size mismatch [recovered]
        panic: size mismatch

goroutine 9 [running]:
testing.func┬À006()
        c:/go/src/testing/testing.go:441 +0x188
github.com/akualab/narray.querySubset(0xc082185f08, 0x2, 0x2, 0xc082006640, 0x3, 0x3, 0x0, 0x0, 0x0)
        c:/GoPath/src/github.com/akualab/narray/narray.go:808 +0xb8
github.com/akualab/narray.(*NArray).SubArray(0xc0820083c0, 0xc082185f08, 0x2, 0x2, 0xc082019f38)
        c:/GoPath/src/github.com/akualab/narray/narray.go:585 +0xd0
github.com/akualab/narray.(*NArray).Vector(0xc0820083c0, 0xc082185f08, 0x2, 0x2, 0xeccb9b148)
        c:/GoPath/src/github.com/akualab/narray/gonum.go:66 +0x4d
github.com/akualab/narray.TestVector(0xc0820d01b0)
        c:/GoPath/src/github.com/akualab/narray/narray_test.go:190 +0x88
testing.tRunner(0xc0820d01b0, 0x694380)
        c:/go/src/testing/testing.go:447 +0xc6
created by testing.RunTests
        c:/go/src/testing/testing.go:555 +0xa92

goroutine 1 [chan receive]:
testing.RunTests(0x602ba0, 0x694320, 0x23, 0x23, 0x45af01)
        c:/go/src/testing/testing.go:556 +0xadd
testing.(*M).Run(0xc0820082d0, 0xc0820086e0)
        c:/go/src/testing/testing.go:485 +0x73
github.com/akualab/narray.TestMain(0xc0820082d0)
        c:/GoPath/src/github.com/akualab/narray/narray_test.go:103 +0x59f
main.main()
        github.com/akualab/narray/_test/_testmain.go:156 +0x1d8
exit status 2
FAIL    github.com/akualab/narray       0.368s
```

**Comment by leoneu** [comment]
fixed, sorry!
